apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: birdeye-addons
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: grafana
            path: charts/grafana
            valueFile: clusters/cluster_1/addons/grafana.yaml
            namespace: monitoring

          - name: ingress-nginx
            path: charts/ingress-nginx
            valueFile: clusters/cluster_1/addons/ingress-nginx.yaml
            namespace: ingress-nginx

          - name: keda
            path: charts/keda
            valueFile: clusters/cluster_1/addons/keda.yaml
            namespace: keda

          - name: loki
            path: charts/loki
            valueFile: clusters/cluster_1/addons/loki.yaml
            namespace: loki

          - name: prometheus
            path: charts/prometheus
            valueFile: clusters/cluster_1/addons/prometheus.yaml
            namespace: monitoring

          - name: statsd-exporter
            path: charts/statsd-exporter
            valueFile: clusters/cluster_1/addons/statsd-exporter.yaml
            namespace: monitoring

          - name: tempo
            path: charts/tempo
            valueFile: clusters/cluster_1/addons/tempo.yaml
            namespace: tempo

          - name: aws-load-balancer-controller
            path: charts/aws-alb-controller
            valueFile: clusters/cluster_1/addons/aws-alb-controller.yaml
            namespace: kube-system

  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/devopsraj178-ops/eks-addons.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - '../../{{valueFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
